### PR TITLE
Create new_idlan.txt

### PR DESCRIPTION
**Pull request by deeeeeelan**
idlan added new folder idlan and new file

### CODE REVIEW

**Review by ashqhal — APPROVED** [review]
Approved

**Review by ehs702 — COMMENTED** [review]
add la a few more lines. thanks. :D

**Comment by deeeeeelan** [comment]
> add la a few more lines. thanks. :D

added. approve pls. thx

**Comment by eyemanusin** [comment]
bayar 1st then approve

**Review by eyemanusin — CHANGES_REQUESTED** [review]
more liness

**Review by Farhanict — APPROVED** [review]

**Review by Farhanict — APPROVED** [review]

**Review by Farhanict — APPROVED** [review]

**Review by Farhanict — APPROVED** [review]
mantap

**Comment by deeeeeelan** [comment]
@eyemanusin approve pls

**Review by eyemanusin — COMMENTED** [review]
approved mantap

**Review by eyemanusin — APPROVED** [review]

**Pull request merged**
